### ISSUE TITLE
Inaccurate latitude values from geoPointFromScreen method

### ISSUE THREAD

**Issue by amirfl** [mousebird/WhirlyGlobe#804]
Using the globe view controller's geoPointFromScreen method, I'm getting latitude values about 2-4 degrees off from the tap location on the globe. Tested on a physical iPhone 6 and the iOS simulator. Longitude values seem pretty accurate.
```

#define radiansToDegrees 57.2957795
- (void)handleLongPress:(UITapGestureRecognizer *)recognizer {
    CGPoint location = [recognizer locationInView:[recognizer.view superview]];

    if (recognizer.state == UIGestureRecognizerStateBegan) {
        NSLog(@"long press began at %f, %f", location.x, location.y);
        
        // find geo location
        MaplyCoordinate maplyCoord;
        BOOL foundGeoCoord = NO;
        if (globeViewC)
            foundGeoCoord = [globeViewC geoPointFromScreen:location geoCoord:&maplyCoord];

        CLLocationCoordinate2D clCoord = [self CLLocationCoordinate2dFromMaplyCoordinate:maplyCoord];
        NSLog(@"tapped at %f, %f",(unsigned long)found.count,clCoord.latitude, clCoord.longitude); // showing inaccurate latitudes
    }
}

- (CLLocationCoordinate2D)CLLocationCoordinate2dFromMaplyCoordinate:(MaplyCoordinate)location{
    return CLLocationCoordinate2DMake(location.y * radiansToDegrees, location.x * radiansToDegrees);
}


```

**Comment by mousebird** [comment]
It's working for me:
2016-12-08 10:04:53.920 AutoTester[40374:38875269] User tapped at screen (391.500000,518.500000), geo (-4.210562,39.956495)
2016-12-08 10:04:53.921 AutoTester[40374:38875269]   geo point from screen (-4.210562,39.956495)

Make sure you're on the latest build.  I think we fixed a bug in that method a few weeks ago.

**Comment by amirfl** [comment]
I've upgraded to the latest nightly build (243) from [mousebird.github.io/WhirlyGlobe/builds/builds.html](url), but still getting this problem unfortunately. Am I using a wrong build of the framework?

**Comment by mousebird** [comment]
That seems right.

Here's the code I used to test:
- (void)globeViewController:(WhirlyGlobeViewController *__nonnull)viewC allSelect:(NSArray *__nonnull)selectedObjs atLoc:(MaplyCoordinate)coord onScreen:(CGPoint)screenPt
{
    NSLog(@"User tapped at screen (%f,%f), geo (%f,%f)",screenPt.x,screenPt.y,coord.x*180/M_PI,coord.y*180/M_PI);
    MaplyCoordinate geoPt;
    [viewC geoPointFromScreen:screenPt geoCoord:&geoPt];
    NSLog(@"  geo point from scree (%f,%f)",geoPt.x*180/M_PI,geoPt.y*180/M_PI);
    
    [self handleSelection:selectedObjs];
}

**Comment by amirfl** [comment]
Thanks, I just found the problem. It was my mistake. I assigned the gesture recognizer to the parent view controller's view instead of to the globe controller's view. Because the main view had a toolbar, its dimensions were different than those of the globe's view and the tap point was incorrect.

**Comment by mousebird** [comment]
Oh, good one.  Thanks for the followup.  I could see that happening to someone else.
