### ISSUE TITLE
View bugs related to mapViewC.setViewExtents(bounding_box)

### ISSUE THREAD

**Issue by pbmorton** [mousebird/WhirlyGlobe#847]
Using the develop branch when using MaplyQuadPagingLayer and MapboxVectorTiles, calling mapViewC.setViewExtents(bbox) successfully constrains the mapview to only display the map in the bbox. You can drag the map around and nothing beyond the bound is displayed. All is good.

Bug 1. Double click near the edge of the map to zoom in. Area beyond the map bounds is now displayed. It should not be displayed because there is no vector tile data available. If you drag the map so the bad area is hidden and drag back the map behaves.

Bug 2. Restart the test. Once the map is displayed double click twice to zoom in. Now rotate the device from portrait to landscape. Pinch to zoom out. This doesn't always work - often you cannot zoom out. It most often fails to zoom out if, when you hold the phone in landscape, you pitch with fingers aligned vertically.

**Comment by pbmorton** [comment]
Bug 3: Enable location tracking and "baseViewC!.changeLocationTrackingLockType(MaplyLocationLockNorthUp)". As the location moves towards the map boundary previously set using setViewExtents(bbox) the view scrolls beyond the bbox. This looks bad and while blank space is shown on screen beyond the desired bbox the pinch and tap gestures misbehave badly. It would be good to have the view extent from setViewExtents() take precedence over location locking and gestures - if location is locked perhaps only reposition the view within the constraints of the bbox. When the location goes outside the bbox send an event to the MaplyLocationTrackerDelegate. The delegate can decide what to do since it set the bbox in the first place. The delegate can disable location tracking for example.

**Comment by mousebird** [comment]
Ranen, can you address #3 and then kick it back to me for the others?
Thanks.

**Comment by rghosh0** [comment]
OK, I made the change in this branch:
https://github.com/mousebird/WhirlyGlobe/tree/hotfix/location-tracking-visibility-and-extents

To test it, in LocationTrackingSimTestCase.swift, in the setUpWithMap method, replace this:

`mapVC.animate(toPosition:MaplyCoordinateMakeWithDegrees(2.3508, 48.8567), height: 0.5, time: 1.0)`

with this:

```
mapVC.setViewExtents(MaplyBoundingBoxMakeWithDegrees(16.38020, 48.20820, 16.38439, 48.21178))
mapVC.setZoomLimitsMin(0.000005, max: 4.0)
mapVC.animate(toPosition:MaplyCoordinateMakeWithDegrees(16.382, 48.2096), height: 0.00001, time: 0.0)
```

**Comment by mousebird** [comment]
Give this a try and let us know if it works.  Reopen if you find problems.

**Comment by pbmorton** [comment]
Ranen, sorry I didn't test and respond to this earlier - I was out of my office. 

Bugs 1 and 2 have not been fixed (on the develop branch). To reproduce these bugs, ensure the viewExtentBbox used in setViewExtents(viewExtentBbox) encompasses the tiles for the map. In other words, there are no tiles outside viewExtentBbox.

The bug 3 fix has problems with the same viewExtentBbox scenario. For example, zoom the map so that say 75% of the full map is visible. Now enable location tracking, set MaplyLocationLockNorthUp and simulate a location close to the edge of the map. Now drag the map so the location is not shown. The displayed part of the map will not move so the location becomes visible. It will only move if it is able to show the location in the middle of the screen.

Perhaps the functionality could be:
IF lockType=MaplyLocationLockNorthUp
    IF current location is inside viewExtentBbox
        IF location can be displayed at screen centre without part of the displayed map being outside viewExtentBbox 
            move map so location is displayed centre
        ELSE
            move map so location is displayed on the screen and the displayed map is within viewExtentBbox 
        ENDIF
    ELSE
        call a MaplyLocationTrackerDelegate func (this is a new delegate func to be aded to the API) notifying the location is outside the viewExtentBbox and cannot be displayed
ENDIF

**Comment by mousebird** [comment]
Ranen, can you look at this one?  Thanks.

**Comment by rghosh0** [comment]
Ok I made pull request #860 to address some of this.  It's in branch hotfix/location-tracking-visibility-and-extents and will be merged into develop.  Here is the description:

Bug 1 fixed.

Bug 2 can not yet reproduce.

Bug 3 partially addressed.  I either lock the screen to the location or I don't -- I don't yet have a fallback for trying to find a view box that contains the location and still is contained by extents.

**Comment by mousebird** [comment]
I merged this in.  Let us know if it works for you.

**Comment by pbmorton** [comment]
I'm using develop commit 84d6a23d592a13f26a33cace465365dab97bd644. I see several problems with gestures. 

As described earlier, the viewExtentBbox used in setViewExtents(viewExtentBbox) encompasses the tiles for the map (i.e. there are no tiles outside viewExtentBbox).  Initially I call maplyViewC.setPosition() setting the centre and height to display as much of the map as possible. 

Problem 1: Double clicking to zoom in does not work anywhere except in the very centre of the map. Pinch gesture to zoom in works (although not perfectly all the time).

Problem 2: Once zoomed in somewhere toward to edge of the map you cannot zoom out with a pinch gesture. You have to scroll the map towards the centre then zoom out.

Problem 3: As soon as my full map is displayed in portrait if I rotate to landscape the map rotates fine but thereafter cannot be dragged or zoomed in or out. All gestures fail.

I'm also seeing issues with location locking not repositioning the map.

Do you need me to put some of my code on bitbucket so you can reproduce these problems more easily?

**Comment by rghosh0** [comment]
Hi Steve,

Can I first confirm which (if any) of the previously listed Bugs 1,2,3 have been resolved? They don't seem to correspond exactly with the new list.

I confirm that in my example, as well, the tiles only exist within the viewExtentsBBox.  I have made a public folder containing my simple ViewController.m demo and the accompanying anchorage.mbtiles tile source file:

https://drive.google.com/drive/folders/0B9Kv4E5NP1kFYXg5a1dMTHRHbmM

For Problems 1 and 2 in the new list, I believe that this was always the behaviour (I used a constrained view extents in an app I developed going back a couple of years, with WhirlyGlobe, and the behaviour was the same).  I'll check with Steve on what he wants to do with these two.

I will check problem 3 now.

In that public folder there is also a video showing some of the behaviour with the code as it is now, although it doesn't show the hand gestures causing the movements.  The last half is showing that Problem 1's description isn't exactly correct, in that you can double-tap anywhere and get a result if the result would be in the view extents, so the double-tap doesn't have to be in the very centre, although it is certainly restricted.

**Comment by rghosh0** [comment]
I can't reproduce Problem 3 from the new list. I'm testing it on an iPad Air, not an iPhone. If you think that posting some of your code would help me reproduce these issues, then by all means.

**Comment by pbmorton** [comment]
Hi Ranen,

Bugs 1 and 2 are not fixed if initially Initially I call maplyViewC.setPosition() setting the centre and height to display as much of the map as possible. Bug 3 is fixed I think, although as you know when lock is enabled the screen will not reposition as the location approaches the map edge.

I've looked at problem 3 again. Some gestures do work, unlike what I saw before. Dragging to move the map always fails but pinch and double tap to zoom do seem to work. My test to do this:
- be in portrait
- create map
- set map centre and zoom to show as much map as possible
- rotate to landscape
- try to drag map in any direction.  No response.

I'll put together a body of code to share for working through the issues. It'll take a little time.

**Comment by rghosh0** [comment]
I debugged it and looked at the internals, and they seem sound.  I believe that the problem is that your zoomOutFull() zooms out too much.  The pan delegate won't pan if it can't reach a valid state. Your zoomOutFull() reaches a state that the pan delegate would never reach, and any incremental change (in any direction) is also invalid. 

To be more specific about the internals: the MaplyPanDelegate withinBounds method calls the mapView's pointOnPlaneFromScreen with the four screen corners, and checks them against the bounds (from setViewExtents).  Because we are zoomed out too far, none of the corners are in bounds.

The problem with your zoomOutFull is that it relies on the findHeight method, which does not take the view extents into account (it's not meant to, and if it did it would return a result signifying invalidity).

It could be useful to have a MaplyViewController method that takes a bbox and makes a best effort to fit it on screen, while respecting the view extents.

**Comment by rghosh0** [comment]
I realized I may have been unclear, so to be more specific: when you start in portrait and rotate to landscape, it is perceived that there is plenty of room to pan up or down. But the problem is, each corner is *horizontally* outside of the view extents (slightly), so it won't happen.

**Comment by pbmorton** [comment]
The zoomOutFull() is trying to zoom to the tiles bounds and not "too far".
Nonetheless I have experimented with reducing the zoom out - see the string
"bugFix" in the zoomOutFull() function. I'm happy to change my
zoomOutFull() function to work around this issue by not quite zooming fully
out (I'll push a change in a minute). In that case this is a workaround for
"problem 3" and we can close it. Thanks Ranen.

Can you reproduce Problem 1 and Problem 2?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by pbmorton** [comment]
One more thing - findHeightToViewBounds() returns vastly different values if the map is started in portrait versus landscape.

**Comment by rghosh0** [comment]
Regarding findHeightToViewBounds(), it's taking the orientation into account. Fitting the same bbox on screen can require a different height for each orientation, depending on the dimensions of the bbox.  There might be some bboxes that give the same height for each orientation.

**Comment by pbmorton** [comment]
Thanks again. I misinterpreted what findHeightToViewBounds() would do. I assumed it would find a height so that the the map did not display in either dimension anything beyond the bbox. I'll rework my test code.

**Comment by mousebird** [comment]
I think we've go these fixed now.
